apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-deployment
  lables: 
    app:superset
spec:
  replicas: 2
  selector:
    matchLabels: 
      app:superset
  template: 
    metadata:
      labels: 
        app:superset
  spec:
    containers:
      -
        name: superset
        image: amancevice/superset
        ports:
        - containerPort: 80
